import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Reservation, Guest } from '../types';

// Helper to format currency
const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(amount);
};

export const generateInvoicePDF = (reservation: Reservation, guest: Guest, propertyName: string = 'Cardea Hotel', userEmail: string): Blob => {
    const doc = new jsPDF();
    const primaryColor = '#1e293b'; // Slate 800

    // Header
    doc.setFontSize(22);
    doc.setTextColor(primaryColor);
    doc.text(propertyName, 14, 20);

    doc.setFontSize(10);
    doc.setTextColor('#64748b'); // Slate 500
    doc.text('INVOICE', 14, 28);
    doc.text(`Invoice #: INV-${reservation.friendlyId || reservation.id.slice(0, 8).toUpperCase()}`, 14, 34);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 40);

    // Bill To
    doc.setFontSize(12);
    doc.setTextColor(primaryColor);
    doc.text('Bill To:', 14, 55);
    doc.setFontSize(10);
    doc.setTextColor('#334155');
    doc.text(guest.fullName, 14, 62);
    doc.text(guest.email || '', 14, 68);
    doc.text(guest.phone || '', 14, 74);

    // Reservation Details
    doc.text('Reservation Details:', 120, 55);
    doc.text(`Confirmation: ${reservation.friendlyId || reservation.id.slice(0, 8).toUpperCase()}`, 120, 62);
    doc.text(`Check-In: ${new Date(reservation.checkIn).toLocaleDateString()}`, 120, 68);
    doc.text(`Check-Out: ${new Date(reservation.checkOut).toLocaleDateString()}`, 120, 74);
    doc.text(`Room: ${reservation.roomNumber}`, 120, 80);

    // Line Items (Simplified for now as we don't have distinct line items in Reservation yet)
    // We will assume "Room Charges" as the main item
    const nights = Math.ceil((new Date(reservation.checkOut).getTime() - new Date(reservation.checkIn).getTime()) / (1000 * 60 * 60 * 24));

    // Explicitly casting autoTable to any because of type definition conflicts in some environments
    (autoTable as any)(doc, {
        startY: 90,
        head: [['Description', 'Qty', 'Unit Price', 'Total']],
        body: [
            ['Room Charges / Night', `${nights} Nights`, 'See Breakdown', formatCurrency(reservation.totalAmount)]
        ],
        theme: 'striped',
        headStyles: { fillColor: primaryColor, textColor: '#ffffff' },
        styles: { textColor: '#334155' }
    });

    // Total
    const finalY = (doc as any).lastAutoTable.finalY + 10;
    doc.setFontSize(12);
    doc.setTextColor(primaryColor);
    doc.text(`Total Stay Amount: ${formatCurrency(reservation.totalAmount)}`, 110, finalY);
    
    if (reservation.accruedAmount !== undefined) {
        doc.text(`Accrued To Date: ${formatCurrency(reservation.accruedAmount)}`, 110, finalY + 8);
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor('#94a3b8');
    doc.text('Thank you for staying with us!', 14, 280);
    doc.text(`Generated by ${userEmail}`, 14, 285);

    return doc.output('blob');
};

export const generateReceiptPDF = (payment: any, guestName: string, propertyName: string = 'Cardea Hotel'): Blob => {
    const doc = new jsPDF();
    const primaryColor = '#1e293b';

    // Header
    doc.setFontSize(22);
    doc.setTextColor(primaryColor);
    doc.text(propertyName, 14, 20);

    doc.setFontSize(10);
    doc.setTextColor('#64748b');
    doc.text('PAYMENT RECEIPT', 14, 28);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 34);

    // Content
    doc.setFillColor('#f8fafc'); // Light slate bg
    doc.rect(14, 45, 180, 60, 'F');

    doc.setFontSize(14);
    doc.setTextColor(primaryColor);
    doc.text(`Total Paid: ${formatCurrency(payment.amount)}`, 20, 60);

    doc.setFontSize(10);
    doc.setTextColor('#475569');
    doc.text(`Payment Method: ${payment.method}`, 20, 70);
    doc.text(`Reference: ${payment.id ? payment.id.slice(0, 8).toUpperCase() : 'N/A'}`, 20, 76);
    doc.text(`Paid By: ${guestName}`, 20, 82);

    if (payment.notes) {
        doc.text(`Notes: ${payment.notes}`, 20, 92);
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor('#94a3b8');
    doc.text('This is an automated receipt.', 14, 280);

    return doc.output('blob');
};
